config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    get "/about" => "topics#about"
    get "/me" => "introductions#show"

    resources :friendships

    resources :introductions # better naming: profiles

    resources :topics do
      resources :comments, :controller => "topic_comments"
      resources :tags, :controller => "topic_tags"

      collection do
        post :bulk_delete
      end

      member do
        post :collect   # TODO: change to post OK
        post :like      # TODO: change to post OK
        post :subscribe # TODO: change to post OK
      end
  end

  namespace :admin do
    resources :topics
    resources :users
    resources :categories
    resources :tags
  end

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  validates_presence_of :name

  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :topic_user_collects, dependent: :destroy
  has_many :collect_users, :through => :topic_user_collects, :source => :user

  has_many :likes, dependent: :destroy
  has_many :like_users , :through => :likes, :source => :user # TODO: rename to like_topics

  has_many :subscribes, dependent: :destroy
  has_many :subscribe_users , :through => :subscribes, :source => :user

  has_one :picture, dependent: :destroy
  has_many :mpictures, dependent: :destroy


  has_many :topic_tag_ships
  has_many :tags, :through => :topic_tag_ships

  accepts_nested_attributes_for :picture, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :mpictures, :allow_destroy => true, :reject_if => :all_blank


  def comment_users
    self.comments.map{ |c| c.user }.uniq
  end

  def tag_list
    self.tags.map{ |t| t.name }.join(",")
  end

  def tag_list=(str)
    arr = str.split(",")

    self.tags = arr.map do |t|
      tag = Tag.find_by_name(t)
      unless tag
        tag = Tag.create!( :name => t )
      end
        tag
    end

  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController

  before_action :check_admin

  def index
    @users = User.all
    @categories = Category.all
    @tags = Tag.all
  end

  protected

  def check_admin
    unless current_user.role == "admin"
      raise ActiveRecord::RecordNotFound #導向404
      redirect_to root_path
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :about]
  before_action :set_post, only: [:show]
  before_action :set_my_post, only: [:edit, :update, :destroy]

  def about
    @topics = Topic.all
    @comments = Comment.all
    @users = User.all
  end

  def bulk_delete
    ids = Array(params[:ids])
    topics = ids.map{ |i| Topic.find_by_id(i) }.compact

    if params[:commit] == "選取刪除"
     topics.each{ |t| t.destroy }
    end
    redirect_to root_path
  end

  def collect
    @topic = Topic.find(params[:id])

    if current_user.is_collect?(@topic)
      TopicUserCollect.find_by(:topic => @topic,:user=>current_user).destroy
    else
      TopicUserCollect.create(:topic => @topic, :user=>current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def like
    @topic = Topic.find(params[:id])

    if current_user.is_like?(@topic)
      Like.find_by(:topic=>@topic,:user=>current_user).destroy
    else
      Like.create(:topic=>@topic,:user=>current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end

  end

  def subscribe
   @topic = Topic.find(params[:id])

    if current_user.is_subscribe?(@topic)
      Subscribe.find_by(:topic=>@topic,:user=>current_user).destroy
    else
      Subscribe.create(:topic=>@topic,:user=>current_user)
    end

    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end


  def index
    @categories = Category.all
    @tags = Tag.all

    if params[:category]
      @category = Category.find(params[:category])
      @topics = @category.topics
    elsif params[:tag]
      @tag = Tag.find(params[:tag])
      @topics = @tag.topics
    else
      @topics = Topic.all
    end

    if current_user && current_user.admin?
      @topics = @topics.all
    elsif current_user
      @topics = @topics.where(["state = ? OR ( state = ? AND user_id = ?) ", "發布", "草稿", current_user.id ])
    else
      @topics = @topics.where(state: "發布").where("scheduled<(?)",Time.now)
    end

    if ["most_comment", "last_comment", "view", "id"].include?( params[:order] )
      @topics = @topics.order("#{params[:order]} DESC")
    else
      @topics = @topics.order("id DESC")
    end

    #找自己話題
    if params[:user]
      @topics = @topics.where(:user_id => params[:user])
    end

    #關鍵字
    if params[:keyword]
      @topics = @topics.where( [ "name like ?", "%#{params[:keyword]}%" ] )
    end

    @topics = @topics.includes(:user, :category, :tags, :comments => :user ).page(params[:page]).per(10)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      flash[:notice] = "新增成功"
      if params[:upload]
        params[:upload].each { |image|
          @topic.mmpictures.create(upload: image)
        }
    end
      redirect_to topics_path
    else
      flash.now[:alert] = "新增失敗"
      render "new"
    end

  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      flash[:notice] = "編輯成功"
      redirect_to topics_path(:page=>params[:page])
    else
      flash.now[:alert] = "編輯失敗"
      render "new"
    end
  end

  def show
    @comment = Comment.new

    # cookies紀錄
    unless cookies["view-topic-#{@topic.id}"]
      @topic.increment!(:view)
      cookies["view-topic-#{@topic.id}"] = true
    end

    session[:topic_id] = @topic.id

  end

  def destroy
    @topic.destroy
    flash[:notice] = "刪除成功"
    redirect_to topics_path(:page=>params[:page])
  end

  private

  def set_post
    if current_user && current_user.admin?
      @topic = Topic.find(params[:id])
    elsif current_user
      @topic = Topic.where(["state = ? OR ( state = ? AND user_id = ?) ", "發布", "草稿", current_user.id ]).find(params[:id])
    else
      @topic = Topic.where(state: "發布").find(params[:id])
    end
  end

  def set_my_post
    if current_user.admin?
      @topic = Topic.find(params[:id])
    else
      @topic = current_user.topics.find(params[:id])
    end
  end

  def topic_params
    params.require(:topic).permit({galleries: []}, :image,:competence,:id,:name,:article,:category_id,:scheduled,:state,:tag_list,:tag_ids=>[], :mpictures_attributes => [:id, :title, :upload, :_destroy],:picture_attributes => [:id, :title, :upload, :_destroy] )
  end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

  def setup_topic(topic)
    topic.build_picture unless topic.picture
    topic
  end


  # 收藏
  def is_topic_collect_class(topic)
    if current_user && current_user.is_collect?(topic)
      "btn-warning"
    else
      "btn-default"
    end
  end

  def is_topic_collect_name(topic)
    if current_user && current_user.is_collect?(topic)
      "已收藏"
    else
      "未收藏"
    end
  end

  def topic_collect_user_name(topic)
    topic.collect_users.map{ |u| u.user_name }.join(" ")
  end


  # Like
  def is_topic_like_class(topic)
    if current_user && current_user.is_like?(topic)
      "btn-info"
    else
      "btn-default"
    end
  end

  def is_topic_like_name(topic)
    if current_user && current_user.is_like?(topic)
      "Like"
    else
      "Unlike"
    end
  end

  def topic_like_user_name(topic)
    topic.like_users.map{ |u| u.user_name }.join(" ")
  end

  # 訂閱
  def is_topic_subscribe_class(topic)
    if current_user && current_user.is_subscribe?(topic)
      "btn-success"
    else
      "btn-default"
    end
  end

  def is_topic_subscribe_name(topic)
    if current_user && current_user.is_subscribe?(topic)
      "subscribe"
    else
      "Unsubscribe"
    end
  end

  def topic_subscribe_user_name(topic)
    topic.subscribe_users.map{ |u| u.user_name }.join(" ")
  end

end

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

  <ul>
  <% @topic.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<%end%>


<div class="form-group">
  <%= t.label :name, "標題:"%>
  <%= t.text_field :name, :class => "form-control"%>
</div>

<div class="form-group">
  <%= t.label :category_id, "文章類別:"%>
  <%= t.collection_select :category_id, Category.all, :id, :name, {}, :class => "form-control"%>
</div>


<div>目前全站有的標籤：
<%Tag.all.each do |t|%>
  <%=t.name%>
<%end%>
</div>
<br>

<div class="form-group">
<%= t.label :tag_list, "加入標籤(請用,來分開)"%>
<%= t.text_field :tag_list, :class => "form-control" %>
</div>

<div class="form-group">
  <%= t.label :article, "文章內容:"%>
  <%= t.text_area :article, :class => "form-control"%>
</div>

<div class="form-group">
<%= t.label :state, "文章是否發布:"%>
<%= t.radio_button :state,"發布",:checked => "checked"%> <%="發布"%>
<%= t.radio_button :state,"草稿"%> <%="草稿"%>
</div>

<div class="form-group">
  <%= t.label :scheduled, "設定發稿時間:"%>
  <%= t.datetime_select :scheduled, :class => "form-control"%>
</div>

<div class="form-group">
  <%= t.label :competence, "權限"%>
  <%=  t.select :competence, [["只有自己可以看","1"],["別人只能看不能留言","2"],["別人可以看也能留言","3"],["限好友才能看跟留言","4"]],  :class => "form-control"%>
</div>


<!-- 一對一，存取在不同的model -->
<%= t.fields_for :picture do |picture_form| %>

  <div class="form-group">
    <%= picture_form.label :upload, "上傳檔案:" %>
    <%= picture_form.file_field :upload%>
  </div>

  <% unless picture_form.object.new_record? %>
    <div class="form-group">
        <%= picture_form.label :_destroy, 'Remove:' %>
        <%= picture_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>

<!-- 多對多，可以上傳多張圖片 -->
<%= t.nested_fields_for :mpictures do |mp| %>
  <div class="form-group">
    <%= mp.file_field :upload%>
    <%= mp.remove_nested_fields_link 'Remove me'%>
  </div>
<% end %>
<%=t.add_nested_fields_link :mpictures, '增加照片'%>
<br>

多張一次上傳檔案
<%= t.label :mmpictures, :class => 'control-label' %>
<%= file_field_tag "upload[]", type: :file, multiple: true %>

-------------------
  <%= file_field_tag "upload[]", type: :file, multiple: true %>

--------carrierwave-----------
 <%= t.file_field :image %>


<script>

  $("#topic_category_id").select2();


  $("#topic_tag_list").select2({
    tags: <%=raw Tag.all.map{|t| t.name}%>,
    tokenSeparators: [',', ' ']
  });


</script>

app/views/topics/about.html.erb
<h1>關於本站</h1>
<h2>會員人數：<%=@users.count%>人</h2>
<h2>話題章數：<%=@topics.count%>篇</h2>
<h2>總回覆筆數：<%=@comments.count%>筆</h2>
<br>
<%=link_to "回首頁", root_path, :class => "btn btn-primary"%>

app/views/topics/collect.js.erb
$("#col").toggleClass("btn-warning")
$("#col").toggleClass("btn-default")

$("#col-name").text("<%= is_topic_collect_name(@topic) %>");
$("#cc").text("<%= topic_collect_user_name(@topic) %>");

$("#col-number").text(<%=@topic.topic_user_collects.count%>);

app/views/topics/edit.html.erb
<h1>編輯文章</h1>
<%=form_for setup_topic(@topic), :url => topic_path(@topic,:page=>params[:page]) do |t|%>
<%=render :partial => "form" , :locals => {:t=>t}%>
<br>
<% if @topic.picture.upload.exists? %>
  <div>
    <%=image_tag( @topic.picture.upload.url(:thumb), alt: "article_p")%>
  </div>
<%end%>
<br>

<%if @topic.mpictures.present?%>
  <%@topic.mpictures.each do |mp|%>
    <div>
      <%=mp.id%>
      <%=link_to image_tag(mp.upload.url(:medium)), mp.upload.url%>
    </div>
    <br>
  <%end%>
<%end%>

<%= t.submit "送出", :class => "btn btn-success"%>
<%=link_to "回首頁", root_path, :class => "btn btn-primary"%>
<%end%>

app/views/topics/index.html.erb
  <div class="row">
    <div class="col-sm-12">
      <div>
        <%= link_to "關於本站", about_path, :class => "btn btn-primary"%>
        <% if current_user %>
        <%= link_to "新增文章", new_topic_path, :class => "btn btn-success"%>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-9">
        <%=link_to "類別選擇", "#", :class => "btn btn-primary", :disabled => true %>
        <%=link_to "All", root_path, :class => "btn btn-info" %>

        <% @categories.each do |c| %>
          <% is_active = ( c.id.to_s == params[:category] )? " btn-warning" : " btn-info" %>

          <%= link_to topics_path(:category => c), :class => "btn #{is_active}" do %>
              <%=  c.name %>
              <span class="badge"><%=c.topics.count%></span>
          <% end %>

        <% end %>
    </div>

    <div class="col-sm-3 right">
      <%= form_tag topics_path, :method => :get do %>
        <%= text_field_tag "keyword" %>
        <%= submit_tag "Search", :class => "btn btn-default"%>
      <% end %>
    </div>
  </div>

<br>

  <div class="row">
    <div class="col-sm-12">
        <%=link_to "標籤選擇", "#", :class => "btn btn-danger", :disabled => true %>
        <%=link_to "All", root_path, :class => "btn btn-danger" %>

        <% @tags.each do |c| %>
          <% is_active = ( c.id.to_s == params[:tag] )? " btn-warning" : " btn-danger" %>

          <%= link_to topics_path(:tag => c), :class => "btn #{is_active}" do %>
              <%=  c.name %>
              <span class="badge"><%=c.topics.count%></span>
          <% end %>

        <% end %>
    </div>
  </div>

<br>

  <div class="row">
    <div class="col-sm-12">
      <%=link_to "按回覆排序", topics_path( :order => "most_comment", :category => params[:category], :tag => params[:tag]), :class => "btn btn-default" %>

      <%=link_to "按回覆時間排序", topics_path( :order => "last_comment", :category => params[:category],:tag => params[:tag]), :class => "btn btn-default" %>

      <%=link_to "按觀看人數排序", topics_path( :order => "view", :category => params[:category], :tag => params[:tag]), :class => "btn btn-default" %>

      <%=link_to "按文章時間排序", topics_path( :order => "id", :category => params[:category], :tag => params[:tag]), :class => "btn btn-default" %>

      <%if current_user != nil %>
        <%=link_to "找自己的話題", topics_path(:user => current_user ), :class => "btn btn-default" %>
      <%end%>
    </div>
  </div>

<br/>

<%= form_tag bulk_delete_topics_path do %>

<table class="table table-striped">
  <tr>
    <%if current_user %>
        <%if current_user.admin? %>
      <td>
          <%= check_box_tag "all_topics" %>
        <%end%>
      </td>
    <%end%>
    <td>討論話題</td>
    <td>分類</td>
    <td>Tag</td>
    <td>參與討論用戶</td>
    <td>觀看</td>
    <td>回覆</td>
    <td>最後回覆時間</td>
    <td>最後回覆用戶</td>
    <td>發帖人</td>
    <%if current_user %>
      <td>狀態</td>
      <td>編輯</td>
      <td>刪除</td>
    <%end%>
  </tr>


  <%@topics.each do |t|%>
      <tr>
        <%if current_user != nil %>
          <%if current_user.role == "admin" %>
        <td>
            <%= check_box_tag "ids[]", t.id, false %>
        <%end%>
        </td>
        <%end%>
        <!-- 主題名稱 -->
        <td>
        <%=link_to t.name, topic_path(t,:page=>params[:page])%>
        </td>
        <!-- 類別 -->
        <td>
        <%=t.category.try(:name)%>
        </td>
        <!-- tag -->
        <td>
          <%t.tags.each do |tag|%>
           <%=tag.name%>
          <%end%>
        </td>
        <!-- 參與討論用戶 -->
        <td>
        <% t.comment_users.each do |c| %>
          <%= link_to introduction_path(c), :id => "pic" do %>
            <%= image_tag( avatar(c), :size => "15x15")%>
            <%= c.user_name %>
          <%end%>
        <%end%>
        </td>
        <!-- 觀看次數 -->
        <td> <%=t.view%> </td>
        <!-- 最多回覆 -->
        <td> <%=t.most_comment%> </td>
        <!-- 最後回覆 -->
        <%t.last_comment = t.comments.last.try(:created_at)%>
        <%t.save%>
        <td> <%=t.last_comment.try(:strftime, "%Y-%m-%d %T") %> </td>
        <!-- 最後回覆用戶 -->
        <td> <%=t.comments.last.try(:user).try(:user_name) %> </td>
        <td>
        <!-- 發帖人 -->
        <%=link_to introduction_path(t.user), :id => "pic" do%>
          <%=image_tag(avatar(t.user),:size => "15x15")%>
          <%=t.user.user_name%>
        <%end%>
        </td>

        <% if current_user && ( current_user == t.user || current_user.admin? ) %>
          <td>
            <%=t.state%>
          </td>
          <td>
            <%=link_to "編輯", edit_topic_path(t,:page=>params[:page]), :class => "btn btn-success" %>
          </td>
          <td>
            <%=link_to "刪除", topic_path(t,:page=>params[:page]), :method => :delete, :class => "btn btn-danger" %>
          </td>
        <% end %>

      </tr>
  <%end%>
</table>
  <% if current_user &&  current_user.admin? %>
    <%= submit_tag "選取刪除" ,:class => "btn btn-danger"%>
  <% end %>
<% end %>

<%= paginate @topics, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm"%>

<script>
$("#all_topics").click(function(){
  if ( $(this).prop("checked")) {
    $("input[name='ids[]']").prop("checked",true)
  } else {
    $("input[name='ids[]']").prop("checked",false)
  }
});
</script>

app/views/topics/like.js.erb
$("#lik").toggleClass("btn-default")
$("#lik").toggleClass("btn-info")

$("#lik-name").text("<%=is_topic_like_name(@topic)%>");
$("#ll").text("<%=topic_like_user_name(@topic)%>");

$("#lik-number").text(<%=@topic.likes.count%>);

app/views/topics/new.html.erb
<h1>新增文章</h1>

<%=form_for setup_topic(@topic), :url => topics_path do |t|%>
  <%=render :partial => "form" , :locals => {:t=>t}%>
  <br/>
  <%= t.submit "送出", :class => "btn btn-success"%>
  <%=link_to "新增新的Tag", new_topic_tag_path(:topic), :class => "btn btn-default"%>
  <%=link_to "回首頁", root_path, :class => "btn btn-primary"%>
<%end%>

app/views/topics/show.html.erb
<h1><%=@topic.name%>  <span class="fb-like"></span>
<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>
</h1>

  <p><%=@topic.article%></p>
    <%if @topic.picture.present? %>
  <div>
    <%=link_to image_tag(@topic.picture.upload.url(:medium)), @topic.picture.upload.url%>
  </div>
  <%end%>
  <%if @topic.mpictures.present?%>
    <%@topic.mpictures.each do |mp|%>
      <div>
        <%=link_to image_tag(mp.upload.url(:medium)), mp.upload.url%>
      </div>
      <br>
    <%end%>
  <%end%>

<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">誰有收藏這篇文章？</h3>
  </div>
  <div class="panel-body" id="cc">
    <%= topic_collect_user_name(@topic) %>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">誰有like這篇文章？</h3>
  </div>
  <div class="panel-body" id="ll">
    <%= topic_like_user_name(@topic) %>
  </div>
</div>


<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">誰有訂閱這篇文章？</h3>
  </div>
  <div class="panel-body" id="ss">
    <%= topic_subscribe_user_name(@topic) %>
  </div>
</div>
<br>

<%=link_to "回首頁", root_path(:page=>params[:page]), :class => "btn btn-primary"%>


<%=link_to collect_topic_path(@topic,:page=>params[:page]), :method=>:post, :class => "btn #{is_topic_collect_class(@topic)} ", remote: true, :id => "col" do%>
  <span id="col-name"><%= is_topic_collect_name(@topic) %></span>
  <span class="badge" id="col-number"><%=@topic.topic_user_collects.count%></span>
<%end%>

<%=link_to like_topic_path(@topic,:page=>params[:page]), :method=>:post, :class => "btn #{is_topic_like_class(@topic)}", remote: true, :id => "lik" do%>
  <span id="lik-name"><%=is_topic_like_name(@topic)%></span>
  <span class="badge" id="lik-number"><%=@topic.likes.count%></span>
<%end%>

<%=link_to subscribe_topic_path(@topic,:page=>params[:page]), :method=>:post, :class => "btn  #{is_topic_subscribe_class(@topic)}", remote: true, :id => "sub" do%>
 <span id="sub-name"><%=is_topic_subscribe_name(@topic)%></span>
<span class="badge" id="sub-number"><%=@topic.subscribes.count%></span>
<%end%>


<br/>
<br/>

<table class="table table-striped" id="user_message">
<tr>
  <td>編號</td>
  <td>頭像</td>
  <td>發布人</td>
  <td>留言內容</td>
  <td>上傳圖片</td>
  <td>發布時間</td>
  <%if current_user != nil %>
  <td>編輯</td>
  <td>刪除</td>
  <%end%>
</tr>

<!-- 留言回覆 -->
<%=render @topic.comments%>

<!-- 留言回覆 -->
<%# @topic.comments.each do |c|
  <%#= render :partial => "comments/comment", :locals => { :comment => c } %>
<%# end %>

<%#= render :partial => "comments/comment", :collection => @topic.comments, :as => :comment %>

</table>

<!-- 文章留言，setup_comment是因為圖片在另一個model -->
<%if current_user != nil && @topic.user.my_friends?(current_user)%>
  <%=form_for setup_comment(@comment), :url => topic_comments_path(@topic), remote: true do |t|%>
    <h2><%= t.label :user_comment, "留言:"%></h2>
    <%= t.text_area :user_comment, :class => "form-control post_content"%>
    <br/>

    <%= t.fields_for :picture do |picture_form| %>
    <p>
    <%= picture_form.label :upload, "上傳檔案" %>
    <%= picture_form.file_field :upload, :class => "post_picture" %>

    <% unless picture_form.object.new_record? %>
        <%= picture_form.label :_destroy, 'Remove:' %>
        <%= picture_form.check_box :_destroy %>
    <% end %>
    </p>
    <% end %>

    <%= t.submit "送出", :class => "btn btn-success"%>
  <%end%>
<%else%>
  <%= link_to('留言請先登入,或是你不是他朋友', new_session_path(:user)) %>
<%end%>

<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>

<%= content_for :head do %>
    <%= tag(:meta, :content => @topic.name, :property => "og:title") %>
    <%= tag(:meta, :content => @topic.article, :property => "og:type") %>
    <% if @topic.picture %>
      <%= tag(:meta, :content => @topic.picture.upload.url, :property => "og:image") %>
    <% end %>
    <%= tag(:meta, :content => topic_url(@topic), :property => "og:url") %>
<% end %>

app/views/topics/subscribe.js.erb
$("#sub").toggleClass("btn-default")
$("#sub").toggleClass("btn-success")
$("#sub-name").text("<%=is_topic_subscribe_name(@topic)%>");
$("#ss").text("<%=topic_subscribe_user_name(@topic)%>");

$("#sub-number").text(<%=@topic.subscribes.count%>);