config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    get "/about" => "topics#about"
    get "/me" => "introductions#show"

    resources :friendships

    resources :introductions # better naming: profiles

    resources :topics do
      resources :comments, :controller => "topic_comments"
      resources :tags, :controller => "topic_tags"

      collection do
        post :bulk_delete
      end

      member do
        post :collect   # TODO: change to post OK
        post :like      # TODO: change to post OK
        post :subscribe # TODO: change to post OK
      end
  end

  namespace :admin do
    resources :topics
    resources :users
    resources :categories
    resources :tags
  end

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  validates_presence_of :name

  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :topic_user_collects, dependent: :destroy
  has_many :collect_users, :through => :topic_user_collects, :source => :user

  has_many :likes, dependent: :destroy
  has_many :like_users , :through => :likes, :source => :user # TODO: rename to like_topics

  has_many :subscribes, dependent: :destroy
  has_many :subscribe_users , :through => :subscribes, :source => :user

  has_one :picture, dependent: :destroy
  has_many :mpictures, dependent: :destroy


  has_many :topic_tag_ships
  has_many :tags, :through => :topic_tag_ships

  accepts_nested_attributes_for :picture, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :mpictures, :allow_destroy => true, :reject_if => :all_blank


  def comment_users
    self.comments.map{ |c| c.user }.uniq
  end

  def tag_list
    self.tags.map{ |t| t.name }.join(",")
  end

  def tag_list=(str)
    arr = str.split(",")

    self.tags = arr.map do |t|
      tag = Tag.find_by_name(t)
      unless tag
        tag = Tag.create!( :name => t )
      end
        tag
    end

  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController

  before_action :check_admin

  def index
    @users = User.all
    @categories = Category.all
    @tags = Tag.all
  end

  protected

  def check_admin
    unless current_user.role == "admin"
      raise ActiveRecord::RecordNotFound #導向404
      redirect_to root_path
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :about]
  before_action :set_post, only: [:show]
  before_action :set_my_post, only: [:edit, :update, :destroy]

  def about
    @topics = Topic.all
    @comments = Comment.all
    @users = User.all
  end

  def bulk_delete
    ids = Array(params[:ids])
    topics = ids.map{ |i| Topic.find_by_id(i) }.compact

    if params[:commit] == "選取刪除"
     topics.each{ |t| t.destroy }
    end
    redirect_to root_path
  end

  def collect
    @topic = Topic.find(params[:id])

    if current_user.is_collect?(@topic)
      TopicUserCollect.find_by(:topic => @topic,:user=>current_user).destroy
    else
      TopicUserCollect.create(:topic => @topic, :user=>current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def like
    @topic = Topic.find(params[:id])

    if current_user.is_like?(@topic)
      Like.find_by(:topic=>@topic,:user=>current_user).destroy
    else
      Like.create(:topic=>@topic,:user=>current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end

  end

  def subscribe
   @topic = Topic.find(params[:id])

    if current_user.is_subscribe?(@topic)
      Subscribe.find_by(:topic=>@topic,:user=>current_user).destroy
    else
      Subscribe.create(:topic=>@topic,:user=>current_user)
    end

    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end


  def index
    @categories = Category.all
    @tags = Tag.all

    if params[:category]
      @category = Category.find(params[:category])
      @topics = @category.topics
    elsif params[:tag]
      @tag = Tag.find(params[:tag])
      @topics = @tag.topics
    else
      @topics = Topic.all
    end

    if current_user && current_user.admin?
      @topics = @topics.all
    elsif current_user
      @topics = @topics.where(["state = ? OR ( state = ? AND user_id = ?) ", "發布", "草稿", current_user.id ])
    else
      @topics = @topics.where(state: "發布").where("scheduled<(?)",Time.now)
    end

    if ["most_comment", "last_comment", "view", "id"].include?( params[:order] )
      @topics = @topics.order("#{params[:order]} DESC")
    else
      @topics = @topics.order("id DESC")
    end

    #找自己話題
    if params[:user]
      @topics = @topics.where(:user_id => params[:user])
    end

    #關鍵字
    if params[:keyword]
      @topics = @topics.where( [ "name like ?", "%#{params[:keyword]}%" ] )
    end

    @topics = @topics.includes(:user, :category, :tags, :comments => :user ).page(params[:page]).per(10)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      flash[:notice] = "新增成功"
      if params[:upload]
        params[:upload].each { |image|
          @topic.mmpictures.create(upload: image)
        }
    end
      redirect_to topics_path
    else
      flash.now[:alert] = "新增失敗"
      render "new"
    end

  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      flash[:notice] = "編輯成功"
      redirect_to topics_path(:page=>params[:page])
    else
      flash.now[:alert] = "編輯失敗"
      render "new"
    end
  end

  def show
    @comment = Comment.new

    # cookies紀錄
    unless cookies["view-topic-#{@topic.id}"]
      @topic.increment!(:view)
      cookies["view-topic-#{@topic.id}"] = true
    end

    session[:topic_id] = @topic.id

  end

  def destroy
    @topic.destroy
    flash[:notice] = "刪除成功"
    redirect_to topics_path(:page=>params[:page])
  end

  private

  def set_post
    if current_user && current_user.admin?
      @topic = Topic.find(params[:id])
    elsif current_user
      @topic = Topic.where(["state = ? OR ( state = ? AND user_id = ?) ", "發布", "草稿", current_user.id ]).find(params[:id])
    else
      @topic = Topic.where(state: "發布").find(params[:id])
    end
  end

  def set_my_post
    if current_user.admin?
      @topic = Topic.find(params[:id])
    else
      @topic = current_user.topics.find(params[:id])
    end
  end

  def topic_params
    params.require(:topic).permit({galleries: []}, :image,:competence,:id,:name,:article,:category_id,:scheduled,:state,:tag_list,:tag_ids=>[], :mpictures_attributes => [:id, :title, :upload, :_destroy],:picture_attributes => [:id, :title, :upload, :_destroy] )
  end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

  def setup_topic(topic)
    topic.build_picture unless topic.picture
    topic
  end


  # 收藏
  def is_topic_collect_class(topic)
    if current_user && current_user.is_collect?(topic)
      "btn-warning"
    else
      "btn-default"
    end
  end

  def is_topic_collect_name(topic)
    if current_user && current_user.is_collect?(topic)
      "已收藏"
    else
      "未收藏"
    end
  end

  def topic_collect_user_name(topic)
    topic.collect_users.map{ |u| u.user_name }.join(" ")
  end


  # Like
  def is_topic_like_class(topic)
    if current_user && current_user.is_like?(topic)
      "btn-info"
    else
      "btn-default"
    end
  end

  def is_topic_like_name(topic)
    if current_user && current_user.is_like?(topic)
      "Like"
    else
      "Unlike"
    end
  end

  def topic_like_user_name(topic)
    topic.like_users.map{ |u| u.user_name }.join(" ")
  end

  # 訂閱
  def is_topic_subscribe_class(topic)
    if current_user && current_user.is_subscribe?(topic)
      "btn-success"
    else
      "btn-default"
    end
  end

  def is_topic_subscribe_name(topic)
    if current_user && current_user.is_subscribe?(topic)
      "subscribe"
    else
      "Unsubscribe"
    end
  end

  def topic_subscribe_user_name(topic)
    topic.subscribe_users.map{ |u| u.user_name }.join(" ")
  end

end

app/views/admin/topics/index.html.erb
<h1>管理者介面</h1>


<!-- 類別＋標籤 -->

<div class="container">
  <div class= "row">
      <div class="col-sm-6">
      <%= link_to "新增類別", new_admin_category_path, :class => "btn btn-success"%>
      <br>
      <br>
        <table class="table table-striped">
          <tr class=" success">
            <td>ID</td>
            <td>類別</td>
            <td>數量</td>
            <td>編輯</td>
            <td>刪除</td>
          </tr>
          <%@categories.each do |c|%>
          <tr>
            <td><%=c.id%></td>
            <td><%=c.name%></td>
            <td><%=c.topics.count%></td>
            <td><%= link_to "編輯", edit_admin_category_path(c),:class => "btn btn-default"%></td>
            <td><%= link_to "刪除", admin_category_path(c), :method => :delete,:class => "btn btn-default"%></td>
          </tr>
           <%end%>
        </table>
      </div>
      <div class="col-sm-6">
      <%= link_to "新增標籤", new_admin_tag_path, :class => "btn btn-success"%>
      <br>
      <br>
        <table class="table table-striped">
          <tr class="warning">
            <td>ID</td>
            <td>標籤</td>
            <td>數量</td>
            <td>編輯</td>
            <td>刪除</td>
          </tr>
          <%@tags.each do |c|%>
          <tr>
            <td><%=c.id%></td>
            <td><%=c.name%></td>
            <td><%=c.topics.count%></td>
            <td><%= link_to "編輯", edit_admin_tag_path(c),:class => "btn btn-default"%></td>
            <td><%= link_to "刪除", admin_tag_path(c), :method => :delete,:class => "btn btn-default"%></td>
          </tr>
           <%end%>
           <tr>
           </tr>
        </table>
      </div>
  </div>
</div>


<h2>會員清單</h2>
<table class="table table-striped">
  <tr class="danger">
    <td>ID</td>
    <td>名稱</td>
    <td>信箱</td>
    <td>個人簡介</td>
    <td>權限</td>
    <td>編輯</td>
  </tr>
  <%@users.each do |u|%>
  <tr>
    <td><%=u.id%></td>
    <td><%=u.user_name%></td>
    <td><%=u.email%></td>
    <td><%=u.introduction.try(:pro)%></td>
    <td><%=u.role%></td>
    <td><%=link_to "編輯", edit_admin_user_path(u), :class => "btn btn-default"%></td>
  </tr>
  <%end%>
</table>
<%=link_to "回首頁", root_path, :class => "btn btn-primary"%>