config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    get "/about" => "topics#about"
    get "/me" => "introductions#show"

    resources :friendships

    resources :introductions # better naming: profiles

    resources :topics do
      resources :comments, :controller => "topic_comments"
      resources :tags, :controller => "topic_tags"

      collection do
        post :bulk_delete
      end

      member do
        post :collect   # TODO: change to post OK
        post :like      # TODO: change to post OK
        post :subscribe # TODO: change to post OK
      end
  end

  namespace :admin do
    resources :topics
    resources :users
    resources :categories
    resources :tags
  end

  root 'topics#index'

end

app/models/introduction.rb
class Introduction < ActiveRecord::Base
  belongs_to :user
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController

  def show
    if params[:id]
      @user = User.find_by_user_name(params[:id])
    else
      @user = current_user
    end

    @users = User.all
  end

  def edit
    @user = current_user
    @user.create_introduction unless @user.introduction
  end

  def update
    @user = current_user
    @user.create_introduction unless @user.introduction

    if @user.introduction.update(intro_params)
      flash[:notice] = "編輯成功"
      redirect_to introduction_path(@user)
    else
      flash.now[:alert] = "編輯失敗(不能留空白)"
      render "edit"
    end
  end

  protected

  def intro_params
    params.require(:introduction).permit(:pro)
  end
end

app/helpers/introductions_helper.rb
module IntroductionsHelper

end

app/views/introductions/edit.html.erb
<br>
<%=form_for @user.introduction, :url => introduction_path(@user.introduction) do |u| %>
  <%= u.label :pro, "內容:"%>
  <%= u.text_area :pro, :class => "form-control"%>
  <br>
  <%= u.submit "送出", :class => "btn btn-success"%>
  <%=link_to "回個人簡介", :back, :class => "btn btn-primary"%>
<%end%>

app/views/introductions/show.html.erb
<h1><%=@user.user_name%>的個人簡介</h1>
<h3> <%=@user.introduction.try(:pro)%> </h3>

<%if current_user != @user && current_user.my_friends?(@user)%>
  <%= link_to "Add Friend", friendships_path(:friend_id => @user.id), :method => :post, :class => "btn #{my_friends_class?(@user)}"%>
  <br>
<%end%>

<!-- friend -->
<%if current_user == @user%>
<h2>All User</h2>
<% @users.each do |user| %>
  <div class="user">
    <p>
      <strong><%= user.user_name %></strong>
      <%= link_to "Add Friend", friendships_path(:friend_id => user.id), :method => :post %>
      <div class="clear"></div>
    </p>
  </div>
<% end %>

<h2>Your Friends Remove</h2>
<ul>
  <%@user.friendships.each do |friendship|  %>

    <%if friendship.status == "好友" %>
    <li>
    <%= friendship.friend.try(:user_name) %>
    <%= link_to "remove", friendship_path(friendship.id), :method => :delete %>
    </li>
    <%end%>
  <% end %>
</ul>

<br>
<br>


<div class="row">


  <div class="col-sm-2">
     <table class="table table-striped">
     <tr class = "info">
        <td>已提出邀請</td>
      </tr>
     <tr>
        <td>
          <% @user.friendships.each do |user|  %>
            <% if user.try(:status)=="邀請"%>
              <li><%=  user.friend.user_name %></li>
            <%end %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>

  <div class="col-sm-3">

    <table class="table table-striped">
      <tr class="warning">
        <td colspan="3">對方提出邀請</td>
      </tr>

      <tr>
        <% @user.inverse_friendships.each do |user|  %>
        <%if user.try(:status)=="邀請"%>
          <td> <%= user.user.user_name %></td>
          <td> <%= link_to "接受", friendships_path(:friend_id => user.user.id,:select=>"yes"), :method => :post, :class => "btn #{my_friends_class?(user)}"%></td>
          <td> <%= link_to "拒絕", friendships_path(:friend_id => user.user.id,:select=>"no"), :method => :post, :class => "btn #{my_friends_class?(user)}"%></td>
          <%end %>
        <% end %>
      </tr>
    </table>
  </div>

  <div class="col-sm-2">
     <table class="table table-striped">
     <tr class = "info">
        <td>成功加好友</td>
      </tr>
     <tr>
        <td>
          <% @user.inverse_friendships.each do |user|  %>
            <% if user.try(:status)=="好友"%>
              <li><%=  user.user.user_name %></li>
            <%end %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>

  <div class="col-sm-3">
     <table class="table table-striped">
     <tr class="danger">
        <td>拒絕加好友</td>
      </tr>
     <tr>
        <td>
          <% @user.inverse_friendships.each do |user|  %>
              <%if user.try(:status)=="拒絕"%>
                <li><%=  user.user.user_name %></li>
              <% end %>
            <% end %>
        </td>
      </tr>
    </table>
  </div>

  <div class="col-sm-2">
     <table class="table table-striped">
     <tr class="danger">
        <td>被拒絕加好友</td>
      </tr>
     <tr>
        <td>
          <% @user.friendships.each do |user|  %>
              <%if user.try(:status)=="拒絕"%>
                <li><%=  user.friend.user_name %></li>
              <% end %>
            <% end %>
        </td>
      </tr>
    </table>
  </div>


</div>

<!-- friend -->
<%end%>
<br>
<br>
<%if current_user != nil%>
  <%= link_to "編輯個人簡介", edit_introduction_path(@user), :class => "btn btn-success"%>
<%end%>
<br>

<h1>發布過文章</h1>
<table class="table table-striped">
  <tr>
    <td>討論話題</td>
    <td>分類</td>
    <td>Tag</td>
    <td>參與討論用戶</td>
    <td>觀看</td>
    <td>回覆</td>
    <td>最後回覆時間</td>
    <td>最後回覆用戶</td>
    <td>發帖人</td>
    <%if current_user %>
      <td>狀態</td>
      <td>編輯</td>
      <td>刪除</td>
    <%end%>
  </tr>
  <%@user.topics.each do |t|%>
    <tr>
      <!-- 主題名稱 -->
      <td><%=link_to t.name, topic_path(t,:page=>params[:page])%></td>
      <!-- 類別 -->
      <td><%=t.category.try(:name)%></td>
      <!-- tag -->
      <td>
        <%t.tags.each do |tag|%>
         <%=tag.name%>
        <%end%>
      </td>
      <!-- 參與討論用戶 -->
      <td>
      <% t.comment_users.each do |c| %>
        <%= link_to c.user_name, introduction_path(c) %>
      <%end%>
      </td>
      <!-- 觀看次數 -->
      <td> <%=t.view%> </td>
      <!-- 最多回覆 -->
      <td> <%=t.most_comment%> </td>
      <!-- 最後回覆 -->
      <%t.last_comment = t.comments.last.try(:created_at)%>
      <td> <%=t.last_comment.try(:strftime, "%Y-%m-%d %T") %> </td>
      <!-- 最後回覆用戶 -->
      <td> <%=t.comments.last.try(:user).try(:user_name) %> </td>
      <td>

      <%=link_to introduction_path(t.user) do%>
        <%=image_tag(Gravatar.new(t.user.email).image_url,:size => "15x15")%>
        <%=t.user.try(:user_name)%>
      <%end%>
      </td>
      <%if current_user != nil %>
        <td>
        <%if current_user == t.user || current_user.admin?%>
          <%=t.state%>
        <%end%>
        </td>
        <td>
          <%if current_user == t.user || current_user.admin?%>
            <%=link_to "編輯", edit_topic_path(t,:page=>params[:page]), :class => "btn btn-success" %>
          <%end%>
        </td>
        <td>
          <%if current_user == t.user || current_user.admin?%>
            <%=link_to "刪除", topic_path(t,:page=>params[:page]), :method => :delete, :class => "btn btn-danger" %>
          <%end%>
        </td>
      <%end%>
    </tr>
  <%end%>
</table>


<h1>回覆過留言</h1>
<table class="table table-striped">
  <tr>
    <td>討論話題</td>
    <td>回覆留言</td>
    <%if current_user != nil %>
    <td>編輯</td>
    <td>刪除</td>
    <%end%>
  </tr>

  <%@user.comments.each do |c|%>
  <tr>
    <td><%=link_to c.topic.try(:name), topic_path(c.topic)%></td>
    <td><%=c.user_comment%></td>
    <%if current_user != nil %>
          <td>
            <%if current_user == @user || current_user.admin?%>
              <%=link_to "編輯", edit_topic_comment_path(:topic_id => c.topic.id,:id=>c), :class => "btn btn-info" %>
            <%end%>
          </td>
          <td>
            <%if current_user == @user || current_user.admin?%>
              <%=link_to "刪除", topic_comment_path(:topic_id => "c.topic.id",:id=>c), :method => :delete, :class => "btn btn-danger" %>
            <%end%>
          </td>
        <%end%>
  </tr>
  <%end%>
</table>


<h1>收藏文章</h1>
<table class="table table-striped">
  <tr>
    <td>討論話題</td>
    <td>分類</td>
    <td>Tag</td>
    <td>參與討論用戶</td>
    <td>觀看</td>
    <td>回覆</td>
    <td>最後回覆時間</td>
    <td>最後回覆用戶</td>
    <td>發帖人</td>
    <%if current_user != nil %>
      <td>狀態</td>
      <td>編輯</td>
      <td>刪除</td>
    <%end%>
  </tr>

  <%@user.collect_topics.each do |t|%>
  <tr>
      <!-- 主題名稱 -->
      <td><%=link_to t.name, topic_path(t,:page=>params[:page])%></td>
      <!-- 類別 -->
      <td><%=t.category.try(:name)%></td>
      <!-- tag -->
      <td>
        <%t.tags.each do |tag|%>
         <%=tag.name%>
        <%end%>
      </td>
      <!-- 參與討論用戶 -->
          <%topic_comment_users = t.comments.map{ |c| c.user }%>
          <%topic_comment_users.uniq!%>
      <td>
      <%  topic_comment_users.each do |c| %>
      <%= link_to c.user_name, introduction_path(c) %>
      <%end%>
      </td>
      <!-- 觀看次數 -->
      <td> <%=t.view%> </td>
      <!-- 最多回覆 -->
      <%t.most_comment = t.comments.count%>
      <td> <%=t.most_comment%> </td>
      <!-- 最後回覆 -->
      <%t.last_comment = t.comments.last.try(:created_at)%>
      <td> <%=t.last_comment.try(:strftime, "%Y-%m-%d %T") %> </td>
      <!-- 最後回覆用戶 -->
      <td> <%=t.comments.last.try(:user).try(:user_name) %> </td>
      <td>

      <%=link_to introduction_path(t.user) do%>
        <%=image_tag(Gravatar.new(t.user.email).image_url,:size => "15x15")%>
        <%=t.user.try(:user_name)%>
      <%end%>
      </td>
      <%if current_user != nil %>
        <td>
        <%if current_user == t.user || current_user.admin?%>
          <%=t.state%>
        <%end%>
        </td>
        <td>
          <%if current_user == t.user || current_user.admin?%>
            <%=link_to "編輯", edit_topic_path(t,:page=>params[:page]), :class => "btn btn-success" %>
          <%end%>
        </td>
        <td>
          <%if current_user == t.user || current_user.admin?%>
            <%=link_to "刪除", collect_topic_path(t,:page=>params[:page]), :class => "btn btn-danger" %>
          <%end%>
        </td>
      <%end%>
  <%end%>
</table>



<h1>like的文章</h1>
<table class="table table-striped">
  <tr>
    <td>討論話題</td>
    <td>分類</td>
    <td>Tag</td>
    <td>參與討論用戶</td>
    <td>觀看</td>
    <td>回覆</td>
    <td>最後回覆時間</td>
    <td>最後回覆用戶</td>
    <td>發帖人</td>
    <%if current_user != nil %>
      <td>狀態</td>
      <td>編輯</td>
      <td>刪除</td>
    <%end%>
  </tr>

  <%@user.like_topics.each do |t|%>
  <tr>
      <!-- 主題名稱 -->
      <td><%=link_to t.name, topic_path(t,:page=>params[:page])%></td>
      <!-- 類別 -->
      <td><%=t.category.try(:name)%></td>
      <!-- tag -->
      <td>
        <%t.tags.each do |tag|%>
         <%=tag.name%>
        <%end%>
      </td>
      <!-- 參與討論用戶 -->
          <%topic_comment_users = t.comments.map{ |c| c.user }%>
          <%topic_comment_users.uniq!%>
      <td>
      <%  topic_comment_users.each do |c| %>
      <%= link_to c.user_name, introduction_path(c) %>
      <%end%>
      </td>
      <!-- 觀看次數 -->
      <td> <%=t.view%> </td>
      <!-- 最多回覆 -->
      <%t.most_comment = t.comments.count%>
      <td> <%=t.most_comment%> </td>
      <!-- 最後回覆 -->
      <%t.last_comment = t.comments.last.try(:created_at)%>
      <td> <%=t.last_comment.try(:strftime, "%Y-%m-%d %T") %> </td>
      <!-- 最後回覆用戶 -->
      <td> <%=t.comments.last.try(:user).try(:user_name) %> </td>
      <td>

      <%=link_to introduction_path(t.user) do%>
        <%=image_tag(Gravatar.new(t.user.email).image_url,:size => "15x15")%>
        <%=t.user.try(:user_name)%>
      <%end%>
      </td>
      <%if current_user != nil %>
        <td>
        <%if current_user == t.user || current_user.admin?%>
          <%=t.state%>
        <%end%>
        </td>
        <td>
          <%if current_user == t.user || current_user.admin?%>
            <%=link_to "編輯", edit_topic_path(t,:page=>params[:page]), :class => "btn btn-success" %>
          <%end%>
        </td>
        <td>
          <%if current_user == t.user || current_user.admin?%>
            <%=link_to "刪除", like_topic_path(t,:page=>params[:page]), :class => "btn btn-danger" %>
          <%end%>
        </td>
      <%end%>
  <%end%>
</table>